version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: psicare-db
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=psicare
      - POSTGRES_USER=psicare_user
      - POSTGRES_PASSWORD=psicare_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - psicare-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  psicare-network:
    driver: bridge